steps:
  - label: 'iohk-ops'
    command: 'scripts/ci.sh -b false'
    agents:
      - "system=x86_64-linux"
    agents:
      system: x86_64-linux

  - label: 'jobsets'
    command: 'nix-build jobsets'
    agents:
      - "system=x86_64-linux"
    agents:
      system: x86_64-linux
